spring:
  # datasource 数据源配置内容，对应 DataSourceProperties 配置属性类
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/liquibase?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # 数据库账号
    password: liujin6966453 # 数据库密码
  # Liquibase 配置内容，对应 LiquibaseProperties 配置项
  liquibase:
    enabled: true # 开启 Liquibase 功能。默认为 true 。
    change-log: classpath:/db/changelog/db.changelog-master.yaml # Liquibase 配置文件地址
    url: jdbc:mysql://127.0.0.1:3306/liquibase?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC # 数据库地址
    user: root # 数据库账号
    password: liujin6966453 # 数据库密码
